spring:
  datasource:
    username: root
    password: shuguangtj
    url: jdbc:mysql://49.234.116.215:13306/gulimall-oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto